lib/init/add-contributors-list.test.js, lib/init/init-content.js
=> Added necessary lines to produce the accurate reference to the specs

lib/util/git.js
Prepend username with `@` in the default commit message
=> Prepend username with `@` in the default commit message

.all-contributorsrc, lib/generate/index.js, lib/generate/index.test.js
Inject some empty content when there are no contributors. Fixes #15
=> Inject some empty content when there are no contributors. Fixes #15

.all-contributorsrc, README.md, lib/util/config-file.js
This was bugging me so I fixed it for you; also reduces a bit of duplication.
PS: You might want to fix the contributors file! https://github.com/jfmengels/all-contributors-cli/commit/b7e5976e445c087ac334b3c2b3721a1a1f90403e
=> Add empty last line to the contributors file.

.all-contributorsrc, README.md, lib/generate/format-contribution-type.test.js, lib/generate/format-contributor.test.js
Updated the question emoji in the lib/generate/format-contribution-type.test.js and lib/generate/format-contributor.test.js files.
=> Update question emoji in tests

README.md
Fixed the all-contributors badge style to be the same as the npm badge style.
=> Fix consistency of badge styles

README.md
Added some general improvements to the README.md file.
=> Add small improvements to README.md

README.md, lib/util/contribution-types.js
Ref https://github.com/kentcdodds/all-contributors/pull/61
---
Let me know if you'd like me to use a different key, and/or if there's anything else to update. Thanks!
=> Add new contribution type: Ideas & Planning

lib/generate/format-contributor.js, lib/generate/format-contributor.test.js
=> fix: Make all contributors names bold

.all-contributorsrc
The auto commit feature being enabled in this repo is really annoying while developing/testing.
=> chore: disable auto commiting changes to contributors

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js, src/init/__tests__/__snapshots__/add-contributors-list.js.snap, src/init/__tests__/add-contributors-list.js, src/init/init-content.js
**What**: Closes #72
**Why**: To make this work nicely for people using prettier
**How**: Updated init and generate files and tests
**Checklist**:
=> add prettier-ignore to output

README.md, src/util/contribution-types.js
**What**: Added `platform` type
**Why**: Approved addition: https://github.com/kentcdodds/all-contributors/issues/68
**How**: 
**Checklist**:
=> Added platform type

README.md
**What**: Docs updated to use `npx`
**Why**: Convenience
**How**: Typing.
**Checklist**:
=> Update docs to include npx

src/util/__tests__/config-file.js, src/util/config-file.js
**What**:
Adds helpful error message when files in project config is overridden or empty
**Why**:
enhances developer experience
**How**:
adds check and error message to util.writeConfig
**Checklist**:
=> adds helpful error message when files is overridden or empty

.all-contributorsrc, README.md
**What**:
Updating config docs for more clarity.
**Why**:
The current docs were not very clear on some of the config options.
**How**:
Update the README.md
**Checklist**:
=> Clarify config docs with example config file

src/util/git.js
**What**:
Without the space, it looks like a little strange.
**Why**:
**How**:
**Checklist**:
=> fix: better output format for git command

README.md
**What**: Add a couple of sentences about running the from the command line with `npx` - they're almost verbetim the "heads up" that @kentcdodds suggested in https://github.com/jfmengels/all-contributors-cli/issues/92#issuecomment-391766876..
**Why**: I was having difficulty understanding how to run the commands and I found this text in issue #92 super helpful - I figured it would be for others too 😄 
**How**: Updated text in README
**Checklist**:
=> Add note about using npx cli command to README

README.md
**What**: remove unnecessary space
**Why**:  generate command will not generate files because of extra space
**How**: remove space
**Checklist**:
=> docs: remove unnecessary space to avoid generation failures

README.md, src/util/contribution-types.js
**What**:
Add Security contribution type, as mentioned in https://github.com/kentcdodds/all-contributors/issues/106 and implemented in https://github.com/kentcdodds/all-contributors/pull/107
Also added user-testing as introduced as part of https://github.com/kentcdodds/all-contributors/pull/97/files
**Why**:
All contributors!
**How**:
Me
**Checklist**:
=> feat: add security (and user-testing) contribution type

.circleci/config.yml, package.json
Follow up from #133 and #132 where release never went out
=> fix: switch over to new org all-contributors

package.json, src/api.js, src/contributors/__tests__/add.js, src/contributors/__tests__/addWithDetails.js, src/contributors/__tests__/fixtures/contributors.json, src/contributors/__tests__/fixtures/index.js, src/contributors/addWithDetails.js
**What**:
Expose 2 API's for use with the All Contributors GitHub bot https://github.com/all-contributors/all-contributors-bot
This is to address: https://github.com/all-contributors/all-contributors/issues/58
**Why**:
We want to create a bot to automate the flow of all contributors
**How**:
By me
**Checklist**:
=> feat: add basic node api for AllContributors GitHub bot

src/init/prompt.js
Raised in https://github.com/all-contributors/all-contributors-bot/issues/57
=> fix: add in contributorsPerLine on init

src/util/contribution-types.js
**What**:
Implements the PM category from https://github.com/all-contributors/all-contributors/pull/199.
**Why**:
Cf. https://github.com/all-contributors/all-contributors/issues/141
**How**:
...
**Checklist**:
=> feat(contribution-types): added Project Management

README.md
**What**:
Fix markdown and spec link.
**Why**:
Markdown is not being formatted. Link is wrong.
**How**:
Markdown :)
**Checklist**:
=> docs(README): spec link fix

src/repo/__tests__/github.js
**What**: The unit test file itself will fail CI
**Why**: CI are now failing
**How**: So I did what linter suggests
**Checklist**:
=> fix(repo): test lint

src/init/commit-conventions.js
**What**:
**Why**:
#202 
**How**:
**Checklist**:
=> feat: Add gitmoji option to commitConventions

.circleci/config.yml
**What**:
Bumps Node.
**Why**:
... To not have failing builds especially due to `semantic-release`.
**How**:
**Checklist**:
=> chore(config): bump node

package.json, src/cli.js
=> chore: make use of inhouse command recommendation implementation

LICENSE.md
**What**:
Adds a license
Closes #254 
**Why**:
There are none on this repo and it would be worth having one.
**How**:
**Checklist**:
=> chore(license): add a license

README.md
**What**: I have created a [`all-contributors-cli`](https://aur.archlinux.org/packages/all-contributors-cli) package on the Arch Linux User Repository (AUR). Feel free to close this PR if you don't want to add a badge.
**Why**: See all-contributors/all-contributors#382 for documentation on the AUR package.
**Checklist**:
=> docs: Add badge for the AUR package version

src/util/contribution-types.js
**What**:
Adds `audio` which wasn't added when https://github.com/all-contributors/all-contributors/pull/371 was merged.
**Why**:
To keep the CLI in sync with the list.
**How**:
Comparing both lists and adding what's missing.
**Checklist**:
=> feat(contribution-types): add missing contribution types

package.json
**What**:
I introduced bug and security fixes (and minor improvements) and I think it would be worthwhile for
this package to use a more up-to-date version.
**Why**:
The current version has known **bugs** that were fixed in `v1.5` including some **security vulnerabilities** in nested deps.
**How**:
Bumping the version to the latest one as of now.
**Checklist**:
=> chore(dep): bumped json-fixer to 1.5.1

src/util/contribution-types.js
**What**:
Add support for mentoring (see https://github.com/all-contributors/all-contributors/issues/423)
**Why**:
**How**:
Added mentoring to [`src/util/contribution-types.js`](https://github.com/all-contributors/all-contributors-cli/blob/master/src/util/contribution-types.js)
**Checklist**:
**Comments**:
If tests are needed, could you point me to the files that I have to change/add?
=> feat(contribution-types): adds mentoring

README.md, src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js, src/init/__tests__/__snapshots__/add-contributors-list.js.snap, src/init/init-content.js
**What**: See commit message and <https://github.com/all-contributors/all-contributors-cli/issues/276>
**Why**: See commit message and discussion at <https://github.com/all-contributors/all-contributors-cli/issues/276>
**How**: Bulk find/replace
**Checklist**:
=> fix: replace markdownlint-enable with markdownlint-restore to restore (vs. enable all) previous rules (fixes #276).

src/repo/github.js
**What**:
Fixed thrown error message in failed GitHub related requests
**Why**:
This accidentally got in as I was copypasting code as part of #277 and we didn't catch it in the PR review.
**How**:
Write code?
**Checklist**:
=> fix: fixed thrown error message

package.json
Resolves: #302
**What**: Bump minimum version of inquirer within `7` from `7.0.4` to `7.3.3`
**Why**: Address CVE-2021-23337 in inquirer->lodash
**How**: `yarn upgrade inquirer@^7.3.3`
**Checklist**:
- [-] Documentation
- [-] Tests
=> chore(deps): CVE-2021-23337 in inquirer->lodash

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/index.js
tobdy -> tbody
**What**:
**Why**:
**How**:
**Checklist**:
=> fix: incorrect usage of `tbody`

README.md
**What**: I noticed some status badges that are not working anymore.
**Why**: Fix some status badges that are not working anymore.
**How**: Provide correct status badges
**Checklist**:
=> chore: fix status badges

src/cli.js
**What**: 
* Adds full `error.stack` if available when there's a crash.
* Fixes #312
**Why**:
* It's harder to debug failures without it.
**How**:
* Update implementation for `onError`.
**Checklist**:
Thank you @tenshiAMD ❤️ #313
=> refactor: log full error stack on error

.github/- Create CODEOWNERS to automate reviewers
**What**:
- Create CODEOWNERS to automate reviewers
**Why**:
- Create CODEOWNERS to automate reviewers
**How**:
- Create CODEOWNERS file
**Checklist**:
=> chore: create CODEOWNERS

src/init/prompt.js, src/util/config-file.js
**What**:
- Setting `commitConvention` default same as `app`
**Why**:
- To avoid conflicts
**How**:
- Update configuration
**Checklist**:
=> fix: set `commitConvention` default same as `app`

src/generate/__tests__/fixtures/contributors.json, src/generate/__tests__/format-contributor.js, src/generate/format-contributor.js
**What**:
- Fix alt value for contributor image with no complete name
**Why**:
- Some contributors do not set complete name
**How**:
- Update code to fix alt value for contributor image with no complete name
**Checklist**:
=> fix: set alt value for contributor image with no complete name

src/util/contribution-types.js
**What**:
- add contribution type `promotion`
- Prerequisite of https://github.com/all-contributors/app/pull/428
**Why**:
**How**:
**Checklist**:
=> feat: add contribution type `promotion`

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js
**What**:
- Fixes https://github.com/all-contributors/cli/issues/340.
**Why**:
- Cleanup table footer to fix some linters
**How**:
- Update implementation
**Checklist**:
=> fix: cleanup table footer

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js
**What**:
This PR improves the looks of contributors table to each cells have more constant width and avatars are vertically aligned.
**Why**:
Currently the table looks not very clean not only on mobile or small screen, but also on large screen depending `contributorsPerLine` value, if it's viewed on main page of repo. (relevant issue: #173)
**How**:
This PR adds `width` and `valign` attributes to contributor cells of the table.
- `width` is calculated by dividing 100% by `contributorsPerLine`.
- `valign` is set to `top`, for better avatar align.
**Checklist**:
**Additional Comment**:
#173 might needs to be not closed or reopened later, because technically this PR doesn't make noticable visual improvement for mobile view.
=> feat: Add `width` and `valign` attributes for cleaner <td>

.all-contributorsrc, README.md, src/util/config-file.js
**What**:
Fixes #359 
**Why**:
Currently you are unable to use the cli
**How**:
add right arguments to the formatConfig() function call
**Checklist**:
=> fix: add correct arguments to the formatConfig() call
