cli.js, lib/util/config-file.js, lib/util/config-file.test.js
Implement first item of issue #6 
> Could not find .all-contributorsrc file
=> Show a helpful message when .all-contributorsrc doesn't exist.

README.md
Updating the README to reflect the correct symbol for the `translation` contribution. (Using `translate` returns `Cannot read property 'symbol' of undefined` when you run `all-contributors generate`.)
=> Fixed translation string

lib/generate/fixtures/contributors.json, lib/generate/format-contributor.js, lib/generate/format-contributor.test.js
Since generate creates a table, pipe characters in names break everything. This change will make it replace all the pipe characters with `&#124;` in just the name part of the template. Added test case as well.
=> Support pipe characters in github names

README.md
Now that we know how to have alt-text on the emojis, we might as well have them on all the ones we show, for consistency and to make stuff clearer.
I do wonder whether we should not simply also add the same text next to the emoji. What do you think?
(By the way, sorry for my lack of presence the last months :disappointed:)
=> docs: add alt text to symbols in the README

lib/contributors/github.js, lib/contributors/github.test.js
Added exception handling when github returns 200 even though the call has been rate-limited. This is the only error I've encountered (just happened to me from work while using this), but there may be others.
=> Github returns 200s for specific errors.

README.md
The script name suggested (`add`) will conflict with users of yarn.
So I modified the suggested name to `append` and provided a yarn example as well.
=> doc: change suggested scripts names

cli.js
=> feat: add --version option

lib/contributors/add.js, lib/contributors/add.test.js
I would type:
`all-contributors add gantman blog` 
and it would get `GantMan` from github.  This caused it to duplicate my user entry over and over.  Making both the find and the update case-insensitive fixes this.  Adding 2 tests as well.
closes #62
=> fix: make find/add case insensitive

src/contributors/__tests__/add.js, src/contributors/add.js, src/contributors/prompt.js, src/generate/__tests__/fixtures/contributors.json, src/generate/__tests__/format-contribution-type.js, src/generate/__tests__/format-contributor.js, src/generate/format-contribution-type.js, src/generate/format-contributor.js
**What**: Fix regression in which if you have any user already added who does not have a github account then the command line fails without any useful error messages.
**Why**: The spirit of all-contributors is such that _all_ contributors get credit, not just those who are github savvy.
**How**: Test driven development
**Checklist**:
NOTE: This situation only arrises when you have manually added non-github users into your `.all-contributorsrc` file. This used to work but regressed in recent versions.
=> Support contributors without github accounts

src/util/check.js
**What**:
If the contributors API returns a bad response show the error message
**Why**:
I ran into this when I was running the check command. The CLI was throwing an error on this line https://github.com/jfmengels/all-contributors-cli/blob/master/src/util/check.js#L28 the response from the API was a 403 and I was getting rate limited. The response was something like
```
{ "message": "API rate limit exceeded" }
```
but there's no prior check to see if either the response is a 200 or if the body is an array. I think it makes sense to throw an error and tell the user what's happening.
**How**:
Updated the code to throw an error if the API response isn't 200.
**Checklist**:
=> fix: surface the message when the check api returns an error

src/util/git.js
**What**:
Fixes #48.
**Why**:
The current usage of `cb` is not very suitable. It expects `(err, ret)`, but `buf/code` is sent as `err`, which results in [`error.message`](https://github.com/jfmengels/all-contributors-cli/blob/master/src/cli.js#L124) to be `undefined`.
```
- git.stderr.on('data', cb)
- git.on('close', cb)
+ git.stderr.on('data', (buf) => {});
+ git.on('close', (code) => {})
```
**How**:
Collect all error messages and return.
**Checklist**:
=> fix: output error messages if git commands failed

src/init/prompt.js
Users, including myself, have put the wrong link in answer to "Where is the repository hosted?". This is a simple fix that should make it clearer what to input.
**What**: Changes prompts in the CLI to be more specific when asking for where the repository is hosted.
**Why**: This is necessary because users (including myself) have become confused on what to put for this. For example, I put "www.github.com/username/repository" for my use of all-contributors-cli, when it should only be the default "www.github.com".
**How**: Changes prompt to be more directional.
**Checklist**:
=> Add clarity to CLI prompt for where repository is hosted

src/cli.js, src/util/config-file.js
**What**:
When a config file is loaded, but the contents cannot be parsed to JSON an error will be thrown. Instead of failing silent: e.g.:
**Why**:
Previously some commands would crash randomly. e.g. `add` with `Cannot read property 'then' of null`.
While other commands e.g. `generate` would succeed but would blow away all your contributors (because it didn't find any)
**How**:
By Me
**Checklist**:
=> infra: better error handling of invalid config file

.eslintrc.js
In the future we should strive to re-enable these
We should also have a lockfile to prevent dependency releases breaking us
=> infra: fix lint

.circleci/config.yml
We should consider using a lockfile to prevent this related to the breaking change in: https://github.com/kentcdodds/eslint-config-kentcdodds/issues/25, fix in #150 also needs cache busted
=> infra: bump cache to get latest deps

src/util/contribution-types.js
**What**:
I added the missing types for "Business development" and "Content".
**Why**:
Because they are specified in [the list](https://all-contributors.js.org/docs/emoji-key#table) but not supported by neither the CLI (until this PR is merged) nor the bot (incoming PR).
**How**:
By adding `business` and `content` to the list.
**Checklist**:
=> feat(contribution-types): added `business` and `content`

src/contributors/prompt.js, src/repo/__tests__/github.js, src/repo/github.js
**What**:
1. Added username validation in inquirer prompt
2. Add validation for wrong username while fetching info from github.
issue #6 
**Why**:
1. More informative errors.
2. Better usability of package .
**How**:
1. Added validation inquirer prompt.
2. throwing error for no username in getUserInfo for github
**Checklist**:
=> fix: add common error handling for missing or wrong username

src/util/config-file.js
Default `config.commitConvention` to `none`.
At the moment, `config.commitConvention` only defaults to `none` during the configuration generation. If the configuration has been generated using an older version of `all-contributors-cli`, that value will be `undefined`. This eventually leads [the following line](https://github.com/all-contributors/all-contributors-cli/blob/2376ada660965e576fb81e788071ee32b7309947/src/util/git.js#L67) to crash with `Cannot read property 'msg' of undefined`. That line is triggered when adding new contributors.
When the configuration file is read, if `commitConvention` is `undefined`, it is set to `none`.
**Checklist**:
=> fix: default commitConvention to 'none'

.all-contributorsrc, README.md, src/generate/__tests__/format-badge.js, src/generate/__tests__/index.js, src/generate/format-badge.js, src/generate/index.js, src/init/__tests__/add-badge.js, src/init/init-content.js
**What**: Badge links to the Contributors section now.
**Why**: Reported in issue #195 
**How**:
1. Run tests :green_heart: 
2. Change tests to consider `#contributors-` as the link
3. Run tests :red_circle: 
4. Fix code to pass the tests: initial badge content and regular expressions.
5. Run tests :green_heart: 
6. I updated README.md as well.
**Checklist**:
Thanks for this opportunity to help with this awesome project!!
=> fix: badge link change

src/cli.js
**What**: Convert username input to string
**Why**: Seems like the cli package will automatically convert "number-like" to numbers
**How**: by using `String(argv._[1])`
**Checklist**:
Reproduce:
```sh
all-contributors add 992939504 content
```
-> `username.toLowerCase is not a function`
=> fix: username might be a number

.all-contributorsrc, README.md, src/cli.js
**What**:
Fix issue #209. The problem was that an `undefined` entity (`argv._[1]`) became a string with a value of `"undefined"`.
**How**:
I simply check if the value is undefined if it is not then I convert it to a string otherwise it stays an `undefined` value.
**Checklist**:
I don't usually program in JS, let me know if there is a more idiomatic way to make this change.
=> fix: add contributions

src/generate/__tests__/index.js, src/generate/index.js, src/init/__tests__/add-badge.js, src/init/init-content.js
**What**:
Fixes #120 
**Why**:
Some repositories want to use HTML templates or custom templates for the badges
**How**:
changed the check done through an hardcoded regex to a simple "is it between these 2 tags"
**Checklist**:
Credits to @simbas
docs are done through https://github.com/all-contributors/all-contributors/pull/312
=> fix: using a custom badge template breaks badge replacement

.all-contributorsrc, README.md, src/generate/__tests__/format-contribution-type.js, src/generate/__tests__/format-contributor.js, src/repo/index.js, src/util/contribution-types.js
**What**: Adding the linking of reviews made by the user
**Why**: Noticed that the link was just an anchor `#review-marceloalves` and since search params can be used on both GitHub/GitLab to filter PR's by reviewer, I thought I would add this
**How**: Followed how `getLinkToIssues` and `getLinkToCommits` were implemented. Added `getLinkToReviews` with URL template + tests
**Checklist**:
=> feat: add review links

src/util/contribution-types.js
**What**: Add `a11y` (Accessibility) contribution type.
**Why**: Discussed in https://github.com/all-contributors/all-contributors/issues/320
**How**: Added a new contribution type in `src/util/contribution-types.js`
**Checklist**:
I’ve yet to figure out how to add myself to the contributors table, can I use the @all-contributors bot to this end?
=> feat: add a11y contribution type

src/generate/__tests__/format-contributor.js, src/generate/format-contributor.js
**What**: Fixed #217 – Removed the unnecessary alternate text from images.
**Why**: This is an accessibility issue. Screen readers read the name of the contributing user twice, which is incorrect. Decorative images are required to have empty alternate text, according to [this W3C spec](https://www.w3.org/WAI/tutorials/images/decorative/).
**How**: Changed alternate text attribute to `alt=""` in tests and implementation.
**Checklist**:
Depends on #221
=> fix: a11y issue by removing unnecessary alternate text (#217)

src/cli.js, src/generate/__tests__/index.js, src/generate/index.js
This parameter allows the user to sort the list of contributors in
alphabetical order of their name.
**What**: This adds a new CLI flag `--contributorsSortAlphabetically`/config option `contributorsSortAlphabetically` that allows you to display the list of contributors in alphabetical order (based on name).
**Why**: This is a feature request that's come up a couple of times, e.g. https://github.com/all-contributors/all-contributors/issues/225
**How**: The order of contributors is preserved in the JSON file. When the list is rendered, check a contributorsSortAlphabetically option (defaulted to false, to preserve existing behaviour) to decide whether to sort the list of contributors before turning into HTML.
Standard TDD: write a test for the new config option, check it fails, edit the …
=> feat(alpha-sort): Add a parameter contributorsSortAlphabetically

src/repo/github.js
**What**:
Pass token to function that needs it
**Why**:
Without it long lists of contributors will error out
**Checklist**:
=> fix(repo): pass optionalPrivateToken to recursive calls

.all-contributorsrc, README.md, src/repo/github.js, src/util/__tests__/url.js, src/util/index.js, src/util/url.js
**What**:
Contributor profile url should be valid url
**Why**:
Please see issue #267
**How**:
Validator was added and used where github profile url is assigned
**Checklist**:
- [N/A] Documentation
=> feat(repo): github profile url should be valid

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js
**What**:
Fixes all-contributors/all-contributors#441 by inserting a newline after the `prettier-ignore-end`.
**Why**:
Without this fix, manual changes are required to all-contributors-cli output to ensure prettier check doesn't fail.
**How**:
Added a single `\n` and updated the tests.
**Checklist**:
=> fix: make all-contributors output Prettier compliant.

src/repo/__tests__/github.js, src/repo/github.js
**What**:
When getting the "API rate limit exceeded" error, this fix shows the original message. Plus it also fixes the current confusing "no login" error message and changes it to "Github username not found".
Fixes #284 
**Why**:
See #284 
**How**:
By the magic of code 😛
Changes done to `github.js` and its test
**Checklist**:
=> fix(github): show the actual error message

src/init/__tests__/add-contributors-list.js
**What**:
Fix new ESlint issues on master branch.
**Why**:
The ESlint rule `jest/no-done-callback` was added  [here](https://github.com/kentcdodds/eslint-config-kentcdodds/commit/d41a11fd7436ce7b4b662daea53d6f3cdf5aa720). Because the package versions are not pinned, the current master branch is failing, and so are all [new PRs](https://github.com/all-contributors/all-contributors-cli/pull/288).
**How**:
Fix new ESlint warning by turning callbacks into promises.
**Checklist**:
=> refactor: return a Promise instead of relying on callback parameter

src/util/contribution-types.js
**What**:
Add a research contribution type with microscope emoji, for people doing literature review, code
prototyping or any other research-related activity.
Part 2/3 of #446
**Why**:
For open science projects or dev projects with a research component, people carrying out research tasks cannot always be acknowledged with the existing types.
Adding the type description and emoji to the list of types available to the CLI tool.
**Checklist**:
I'm not really familiar with npm so I'm not sure how to install my modified version of the cli tool to test it. Any help?
Bot PR following.
=> feat(contribution-types): add research contribution type

src/repo/index.js
This commit adds the possibility to specify the private token via the
ALL_CONTRIBUTORS_PRIVATE_TOKEN environment variable. If the environment
variable is not set it will fall back to the previous behavior and check
for PRIVATE_TOKEN instead.
Closes #294
=> feat: add namespaced token

other/MAINTAINING.md, package.json, src/cli.js
**What**: CLI usage was specified in the code, but in a wrong way.
This PR allows for the subcommands usage message to be displayed properly.
It also replace `cli.js` by `all-contributors` in the usage messages.
**Why**: in order to fix the aforementioned usage message issues
**How**: in Javascript 😊
**Checklist**:
**Behaviour BEFORE** this PR:
```
$ all-contributors add --help
add a new contributor
Options :
...
```
**Behaviour AFTER** this PR:
```
$ all-contributors add --help
Add a new contributor
USAGE: all-contributors add <username> <comma-separated contributions>
Options :
...
```
My initial motivation for this PR was to make it explicit in `all-contributors add --help`
that several contributions could be specified at once,
but **comma-separated and not space-separated**,
as I have …
=> fix: scriptName + improving usage messages

src/repo/github.js
Hey all! I think I found and fixed a small bug; using this PR to start a discussion. When I tried updating Redwood's all contributors table, I got a `Only absolute URLs are supported` error, so I dug in a bit. This is the command I ran:
```
yarn all-contributors check --config .all-contributorsrc
```
And here's the `.all-contributorsrc` file: https://github.com/redwoodjs/redwood/blob/main/tasks/all-contributors/.all-contributorsrc.
I stepped through the code and narrowed it down; the error's happening in the `getNextLink` function. Here's the value for `link`:
```js
'<https://api.github.com/repositories/191051391/contributors?per_page=100&page=1>; rel="prev", <https://api.github.com/repositories/191051391/contributors?per_page=100&page=3>; rel="next", …
```
=> fix: trim `nextLink` before slicing

src/generate/__tests__/format-contributor.js, src/generate/format-contributor.js
**What**:
- Set alt value for contributor image (
**Why**:
- Alt value is a must
**How**:
- Update code to set alt value for contributor image
**Checklist**:
=> feat: set alt value for contributor image

src/generate/__tests__/__snapshots__/index.js.snap, src/generate/__tests__/index.js, src/generate/index.js
**What**: Adding support for a wrapper template that allows for a minimalist version of the contributors log. See original [issue](https://github.com/all-contributors/all-contributors/issues/85)
**Why**: Modified the wrapping template from the defaulted 'table' to what ever the user supplies in their configuration
**How**: A simple if during the generation of the list wrapping. For a working sample, check this [repo](https://github.com/jdalrymple/all-contributors-wrapper-sample). After running the install, you may need to run `yarn build` from within the node_modules/all-contributors-cli directory to have access to the cli commands.
**Checklist**:
=> feat: add `wrapperTemplate` option

package.json, src/util/__tests__/__stubs__/.prettierrc.json, src/util/__tests__/formatting.js, src/util/config-file.js, src/util/formatting.js
**What**: If the user has the `prettier` package available in their project _and_ has a Prettier config file (e.g. `.prettierrc.json`), [Prettier](https://prettier.io) will be used to write `.allcontributorsrc` files.
**Why**: See #347. 
**How**: Adds `prettier` as an optional dependency. Augments the config writing logic to:
1. Attempt to `require('prettier')`
2. Find the nearest Prettier config for the file with `prettier.resolveConfigFile.sync`
3. Use Prettier to format the file with that config
...falling back to the traditional `JSON.stringify(content, null, 2)` if any of that fails.
**Checklist**:
Are `optionalDependencies` the way to go? I can never keep track of the latest preferences around optionals/peers/etc.
=> feat: use Prettier to write config file, if possible
